### ISSUE TITLE
涛哥你也提前整毕设啊

### ISSUE THREAD

**Issue by bianyukun1213** [looooading/algorithms#1]
都开始研究算法了，高级！俺也在整毕设。俺们环境的“技术活儿”也就是画画 CAD 了。

**Comment by looooading** [comment]
不提前没办法呀，我本来方向是设计方向，这是电器方向的课题。而且老师还说要实行末尾淘汰制，最后要挂掉两个人。这算法其实也已经很久了，都是基础算法，我们直接拿过来用就行。主要还是考验我们把各个环节串联起来，然后仿真。也就是说我们真正要生产的东西我还一点没做出来呢QAQ。CAD也不好画啊，我之前的课程设计就是CAD画离合器。

**Comment by bianyukun1213** [comment]
我测……毕设实行末尾淘汰？！挂的那俩咋整？延毕？

**Comment by looooading** [comment]
对的，开会说的就是延毕两个。发件人: ***@***.*** ***@***.***> 代表 边宇琨 ***@***.***>发送时间: 星期日, 一月 28, 2024 11:20:09 下午收件人: algorithms ***@***.***>抄送: 1275318444 ***@***.***>; comment ***@***.***>主题: Re: [looooading/algorithms] 涛哥你也提前整毕设啊 (Issue #1)
我测……毕设实行末尾淘汰？！挂的那俩咋整？延毕？

**Comment by looooading** [comment]
对的，我们开会当时说的就是八个里面延毕两个。
